# P4Perform program to test
p4prog: '/home/cs344-2/P4Perform/bmv2_router/router.p4'
# p4prog: '/home/cs344-2/P4Perform/basic/basic.p4'
test-times: 5

# Calibration method can be loopback or calib
# If it's loopback, then no need for calib-prog, but must include a loopback interface
calib: 'loopback'
calib-prog: '/home/cs344-2/P4Perform/bmv2-calib/calib.p4'
loopback-if: 'nf2'

# How to find the DUT 
dut-mac: '00:0f:53:0c:56:70'
dut-host: 'cs344-2@packet-5.stanford.edu'
dut-port: 6666
dut-workdir: '/home/cs344-2/P4Perform'

# Agent program to manage the DUT's tables
agent-prog: '/home/cs344-2/performance/sw/performance_sw/agent.py'
agent-port: 9999
